# Generated by Django 5.0.7 on 2024-08-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwdmgr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicons'),
        ),
    ]
